name: Deploy to Cloud Run Functions

on:
  push:
    branches: [main]

env:
  PROJECT_ID: chrome-reserve-462911-k1
  REGION: asia-northeast1
  FUNCTION_NAME: github-actions-cicd
  WORKLOAD_IDENTITY_PROVIDER: "projects/312483508370/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
  SERVICE_ACCOUNT: "github-actions-sa@chrome-reserve-462911-k1.iam.gserviceaccount.com"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run Functions
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }} \
            --gen2 \
            --runtime=python311 \
            --region=${{ env.REGION }} \
            --source=. \
            --entry-point=github_actions_cicd \
            --trigger-http \
            --no-allow-unauthenticated \
            --memory=256Mi \
            --timeout=600s

      - name: Get function URL
        id: get-url
        run: |
          FUNCTION_URL=$(gcloud functions describe ${{ env.FUNCTION_NAME }} \
            --gen2 \
            --region=${{ env.REGION }} \
            --format 'value(serviceConfig.uri)')
          echo "url=$FUNCTION_URL" >> $GITHUB_OUTPUT

      - name: Test deployment
        run: |
          curl -f ${{ steps.get-url.outputs.url }}/ || exit 1

      - name: Comment deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Cloud Run Functions Deployment successful!**

            Function URL: ${{ steps.get-url.outputs.url }}

            - Health Check: ${{ steps.get-url.outputs.url }}/
            - API Info: ${{ steps.get-url.outputs.url }}/api/info
            - Hello API: ${{ steps.get-url.outputs.url }}/api/hello?name=GitHubActions
            - Echo API: ${{ steps.get-url.outputs.url }}/api/echo (POST)`
            })
